apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 4Gi
  volumeName: pv-pihole
